# Utiliser une image Python légère
FROM python:3.8.10-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

COPY requirements.txt .

# Installer les dépendances nécessaires
RUN pip install --no-cache-dir -r requirements.txt

# Copier les fichiers dans le conteneur
COPY . .

EXPOSE 8000

# Lancer l'application avec uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]