runtime: python311  # Utilisez la version de Python que vous avez installée
env: standard
instance_class: F4_1G
# instance_class: F4_1G  # Utilisez F4_1G pour plus de mémoire
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
# Commande de démarrage pour Google App Engine
entrypoint: gunicorn -b :$PORT -w 2 main:app # Entry point de l'application (main.py)

# accès aux APIs et services nécessaires
env_variables:
  GOOGLE_CLOUD_PROJECT: "sublimepick1"  # ID  projet
  # BUCKET_NAME: "sublime_bucket_2024"    # Nom  Cloud Storage bucket
  # STORAGE_PATH: "data-test-api-application"  # Répertoire dans bucket
  BUCKET_NAME: "sublime_bucket_bis"
  STORAGE_PATH: "10/reviews/merged_product_reviews.json"
  PYTHONPATH: .:backend:backend/helpers

service_account: sublimepick1@appspot.gserviceaccount.com

handlers:
  - url: /static
    static_dir: frontend/static

  - url: /.*
    script: auto

readiness_check:
  app_start_timeout_sec: 1800
